[pytest]
pythonpath = tests
asyncio_mode = strict
asyncio_default_fixture_loop_scope = function
markers =
    scraper: scraper tests, either bs4 or playwright
    playwright: tests that use Playwright to run
    calcy: desktop calculator app tests