name: Pytest Scraper Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  pytest-scraper-tests:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        pip install pytest-playwright playwright-stealth pytest-asyncio requests pytz beautifulsoup4

    - name: Initialize Playwright
      run: playwright install --with-deps

    - name: Run Pytest Scraper Tests in Linux (Ubuntu)
      run: |
        mkdir -p public
        pytest tests/scrapers --junit-xml=reports/scrapers-lin-report.xml -o junit_logging=all --html=public/index.html --self-contained-html
      if: always()

    - name: Setup Pages
      if: always()
      uses: actions/configure-pages@v5

    - name: Upload Github Pages artifact
      if: always()
      uses: actions/upload-pages-artifact@v3
      with:
          path: 'public'

    - name: Deploy to GitHub Pages
      if: always()
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Upload Scrapers Linux Test Report XML
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: scrapers-lin-report-xml
        path: reports/scrapers-lin-report.xml

        
